<?php /* @var $viewModel \T4webCalendar\Controller\ViewModel\ShowViewModel */ ?>
<?php $viewModel = $this->viewModel()->getCurrent(); ?>

<?php $this->headScript()->appendFile($this->basePath() . '/js/t4web-calendar/jquery-ui-1.9.2.custom.min.js');?>
<?php $this->headScript()->appendFile($this->basePath() . '/js/t4web-calendar/jquery-ui.multidatespicker.js');?>
<?php $this->headScript()->appendFile($this->basePath() . '/js/t4web-calendar/add.js');?>

<div class="page-header">
    <div class="row">
        <h1 class="col-xs-12 col-sm-4 text-center text-left-sm"><i class="fa fa-calendar page-header-icon"></i>&nbsp;&nbsp;Holiday calender</h1>
    </div>
</div>

<style>
    .ui-state-highlight {
        background: none repeat scroll 0 0 #e63c3b !important;
    }

    .ui-datepicker .ui-state-highlight a {
        color: #fff !important;
        text-decoration: none;
    }

    .ui-datepicker-group {
        border: 1px solid #eee;
        float: left;
        margin: 20px 25px;
        width: 210px;
    }

    .ui-datepicker {
        border: none;
    }

    .ui-datepicker-title {
        width: 208px;
    }
    .ui-datepicker-next, .ui-datepicker-prev {
        display: none;
    }

    .col-xs-12:after {
        clear: both;
    }
    .clearfix{
        zoom: 1;
    }
    .clearfix:after{
        clear: both;
        content: '';
        display: block;
    }
</style>

<div class="row">
    <div class="col-xs-12">

        <div class="panel-body" style="height: 800px;">
            <div id="bs-datepicker-inline"><div class="clearfix"></div></div>
            <div class="clearfix"></div>
        </div>

    </div>

</div>