<?php /* @var $viewModel \T4webCalendar\Controller\ViewModel\ShowViewModel */ ?>
<?php $viewModel = $this->viewModel()->getCurrent(); ?>

<?php $this->headScript()->appendFile($this->basePath() . '/js/t4web-calendar/jquery-ui-1.9.2.custom.min.js');?>
<?php $this->headScript()->appendFile($this->basePath() . '/js/t4web-calendar/jquery-ui.multidatespicker.js');?>
<?php $this->headScript()->appendFile($this->basePath() . '/js/t4web-calendar/add.js');?>

<?php $this->headLink()->prependStylesheet($this->basePath() . '/css/t4web-calendar/calendar.css');?>

<div class="page-header">
    <div class="row">
        <h1 class="col-xs-12 col-sm-4 text-center text-left-sm"><i class="fa fa-calendar page-header-icon"></i>&nbsp;&nbsp;Holiday calender</h1>
    </div>
</div>

<div class="row">
    <div class="col-xs-12">

        <div class="panel panel-dark widget-profile datapicker-calendar" id="bs-datepicker-inline"></div>

    </div>
</div>